### ISSUE TITLE
reference paper

### ISSUE THREAD

**Issue by pribadihcr** [frkl/active-learning#1]
Hi @frkl ,

Is there any reference paper for active learning implementation?

Thanks

**Comment by frkl** [comment]
Vanilla active learning, that is selecting an example with maximum entropy after softmax works the best, resulting in 60%~70% reduction in the amount of training examples. Fancy approaches don't seem to work as well as vanilla active learning. These are empirical results, no formal paper.

**Comment by frkl** [comment]
Algorithm published as [arxiv.org/abs/1711.01732](url)
